"""Generate markdown view files from Akemi graph nodes.

Replaces rebuild-views.sh with pure Python.  Produces six view files
in ``.akemi/graph/views/``:

  - ``architecture.md``  -- domains, module dependencies, tech stack
  - ``api-surface.md``   -- API endpoint listing
  - ``test-coverage.md`` -- covered / not-covered map
  - ``dependency-tree.md`` -- module dependency tree with all ref types
  - ``tech-stack.md``    -- technology table
  - ``backlog.md``       -- SAFe work items: PIs, backlog by state, traceability
"""

from __future__ import annotations

from pathlib import Path

from .node import NodeFile, read_all_nodes
from .paths import now_iso


def rebuild_views(akemi_dir: str | Path) -> str:
    """Generate all 6 view files in ``.akemi/graph/views/``.

    Returns a summary string.
    """
    akemi_dir = Path(akemi_dir)
    nodes_dir = akemi_dir / "graph" / "nodes"
    views_dir = akemi_dir / "graph" / "views"
    views_dir.mkdir(parents=True, exist_ok=True)

    nodes = read_all_nodes(nodes_dir)
    timestamp = now_iso()

    (views_dir / "architecture.md").write_text(
        _architecture_view(nodes, timestamp), encoding="utf-8"
    )
    (views_dir / "api-surface.md").write_text(
        _api_surface_view(nodes, timestamp), encoding="utf-8"
    )
    (views_dir / "test-coverage.md").write_text(
        _test_coverage_view(nodes, timestamp), encoding="utf-8"
    )
    (views_dir / "dependency-tree.md").write_text(
        _dependency_tree_view(nodes, timestamp), encoding="utf-8"
    )
    (views_dir / "tech-stack.md").write_text(
        _tech_stack_view(nodes, timestamp), encoding="utf-8"
    )
    (views_dir / "backlog.md").write_text(
        _backlog_view(nodes, timestamp), encoding="utf-8"
    )

    return f"Views rebuilt at {timestamp}"


# ---------------------------------------------------------------------------
# Internal view builders
# ---------------------------------------------------------------------------


def _nodes_of_kind(nodes: dict[str, NodeFile], kind: str) -> list[NodeFile]:
    """Return nodes of a given kind, sorted by ID for deterministic output."""
    return sorted(
        (n for n in nodes.values() if n.kind == kind),
        key=lambda n: n.id,
    )


def _architecture_view(nodes: dict[str, NodeFile], timestamp: str) -> str:
    """Generate ``architecture.md``.

    Sections:
      - Domains: each domain with its contained modules
      - Module Dependencies: ``mod-a -> mod-b, mod-c``
      - Tech Stack: technology name and version
    """
    lines: list[str] = [
        "# Architecture Overview",
        "",
        f"> Auto-generated by Akemi at {timestamp}. Do not edit manually.",
        "",
    ]

    # --- Domains ---
    lines.append("## Domains")
    lines.append("")

    domains = _nodes_of_kind(nodes, "domain")
    if not domains:
        lines.append("_No domains defined yet._")
    else:
        for dom in domains:
            lines.append(f"### {dom.name} ({dom.id})")
            contains = [r.to for r in dom.refs if r.rel == "contains"]
            for target in contains:
                lines.append(f"- {target}")
            lines.append("")

    # --- Module Dependencies ---
    lines.append("## Module Dependencies")
    lines.append("")

    modules = _nodes_of_kind(nodes, "module")
    if not modules:
        lines.append("_No modules defined yet._")
    else:
        for mod in modules:
            deps = [r.to for r in mod.refs if r.rel == "depends_on"]
            if deps:
                lines.append(f"{mod.id} -> {', '.join(deps)}")
    lines.append("")

    # --- Tech Stack ---
    lines.append("## Tech Stack")
    lines.append("")

    techs = _nodes_of_kind(nodes, "technology")
    if not techs:
        lines.append("_No technologies defined yet._")
    else:
        for tech in techs:
            version = tech.extra.get("version", "")
            if version:
                lines.append(f"- {tech.name} {version}")
            else:
                lines.append(f"- {tech.name}")

    lines.append("")
    return "\n".join(lines)


def _api_surface_view(nodes: dict[str, NodeFile], timestamp: str) -> str:
    """Generate ``api-surface.md``.

    Lists all API nodes with method, path_pattern, and auth fields.
    """
    lines: list[str] = [
        "# API Surface",
        "",
        f"> Auto-generated by Akemi at {timestamp}. Do not edit manually.",
        "",
    ]

    apis = _nodes_of_kind(nodes, "api")
    if not apis:
        lines.append("_No API endpoints defined yet._")
    else:
        for api in apis:
            method = api.extra.get("method", "")
            path_pattern = api.extra.get("path_pattern", "")
            auth = api.extra.get("auth", "")
            lines.append(
                f"- **{method} {path_pattern}** ({api.id}) - auth: {auth}"
            )

    lines.append("")
    return "\n".join(lines)


def _test_coverage_view(nodes: dict[str, NodeFile], timestamp: str) -> str:
    """Generate ``test-coverage.md``.

    Sections:
      - Covered: entities that have test nodes with ``tests`` refs
      - Not Covered: classes/functions without any test coverage
    """
    lines: list[str] = [
        "# Test Coverage Map",
        "",
        f"> Auto-generated by Akemi at {timestamp}. Do not edit manually.",
        "",
    ]

    # Collect all tested entity IDs and the test nodes that cover them.
    test_nodes = _nodes_of_kind(nodes, "test")

    # Map: tested_entity_id -> list of test node IDs that cover it.
    tested_by: dict[str, list[str]] = {}
    for tn in test_nodes:
        for ref in tn.refs:
            if ref.rel == "tests":
                tested_by.setdefault(ref.to, []).append(tn.id)

    # --- Covered ---
    lines.append("## Covered")
    lines.append("")

    if not tested_by:
        lines.append("_No test mappings yet._")
    else:
        for entity_id in sorted(tested_by.keys()):
            for test_id in sorted(tested_by[entity_id]):
                lines.append(f"- {entity_id} <- {test_id}")
    lines.append("")

    # --- Not Covered ---
    lines.append("## Not Covered")
    lines.append("")

    tested_ids = set(tested_by.keys())
    uncovered: list[NodeFile] = []
    for node in sorted(nodes.values(), key=lambda n: n.id):
        if node.kind in ("class", "function") and node.id not in tested_ids:
            uncovered.append(node)

    if not uncovered:
        lines.append("_All entities have test coverage._")
    else:
        for node in uncovered:
            lines.append(f"- {node.id} ({node.name}) - NO TESTS")

    lines.append("")
    return "\n".join(lines)


def _dependency_tree_view(nodes: dict[str, NodeFile], timestamp: str) -> str:
    """Generate ``dependency-tree.md``.

    For each module, lists ALL refs (not just depends_on).
    """
    lines: list[str] = [
        "# Dependency Tree",
        "",
        f"> Auto-generated by Akemi at {timestamp}. Do not edit manually.",
        "",
    ]

    modules = _nodes_of_kind(nodes, "module")
    if not modules:
        lines.append("_No modules defined yet._")
    else:
        for mod in modules:
            lines.append(f"## {mod.name} ({mod.id})")
            if mod.refs:
                for ref in mod.refs:
                    lines.append(f"- --{ref.rel}--> {ref.to}")
            lines.append("")

    lines.append("")
    return "\n".join(lines)


def _tech_stack_view(nodes: dict[str, NodeFile], timestamp: str) -> str:
    """Generate ``tech-stack.md``.

    Renders a markdown table: ``| Technology | Category | Version |``
    """
    lines: list[str] = [
        "# Tech Stack",
        "",
        f"> Auto-generated by Akemi at {timestamp}. Do not edit manually.",
        "",
    ]

    techs = _nodes_of_kind(nodes, "technology")
    if not techs:
        lines.append("_No technologies defined yet._")
    else:
        lines.append("| Technology | Category | Version |")
        lines.append("|-----------|----------|---------|")
        for tech in techs:
            category = tech.extra.get("category", "n/a") or "n/a"
            version = tech.extra.get("version", "n/a") or "n/a"
            lines.append(f"| {tech.name} | {category} | {version} |")

    lines.append("")
    return "\n".join(lines)


# Canonical state order for the backlog view.  Unknown states are
# appended alphabetically after these.
_BACKLOG_STATE_ORDER: tuple[str, ...] = (
    "funnel",
    "analyzing",
    "backlog",
    "refining",
    "ready",
    "in_progress",
    "implementing",
    "done",
)


def _ref_targets(node: NodeFile, rel: str) -> list[str]:
    """Return the targets of all refs on *node* with relationship *rel*."""
    return [r.to for r in node.refs if r.rel == rel and r.to]


def _story_points(node: NodeFile) -> str:
    """Return the story point estimate as a string, or '' if unset.

    Prefers ``story_points``, falls back to the legacy ``points`` field.
    """
    value = node.extra.get("story_points")
    if value in (None, ""):
        value = node.extra.get("points")
    if value in (None, ""):
        return ""
    return str(value)


def _wsjf_score(node: NodeFile) -> str:
    """Return the WSJF score from the node's wsjf block, or '' if unset."""
    wsjf = node.extra.get("wsjf")
    if not isinstance(wsjf, dict):
        return ""
    score = wsjf.get("score")
    if score in (None, ""):
        return ""
    return str(score)


def _backlog_view(nodes: dict[str, NodeFile], timestamp: str) -> str:
    """Generate ``backlog.md``.

    Sections:
      - Program Increments: each PI with its iterations and objectives
      - Backlog by State: features and stories grouped by state field
      - Traceability: epic -> capability -> feature -> story chains
        derived from realizes refs
    """
    lines: list[str] = [
        "# Backlog",
        "",
        f"> Auto-generated by Akemi at {timestamp}. Do not edit manually.",
        "",
    ]

    # --- Program Increments ---
    lines.append("## Program Increments")
    lines.append("")

    pis = _nodes_of_kind(nodes, "pi")
    iterations = _nodes_of_kind(nodes, "iteration")
    objectives = _nodes_of_kind(nodes, "objective")

    if not pis:
        lines.append("_None yet._")
        lines.append("")
    else:
        for pi in pis:
            start = str(pi.extra.get("start") or "?")
            end = str(pi.extra.get("end") or "?")
            lines.append(f"### {pi.name} ({pi.id}): {start} to {end}")
            lines.append("")

            pi_iters = [
                it for it in iterations if pi.id in _ref_targets(it, "part_of")
            ]
            lines.append("Iterations:")
            if not pi_iters:
                lines.append("- _None yet._")
            else:
                for it in pi_iters:
                    number = it.extra.get("number", "?")
                    it_start = str(it.extra.get("start") or "?")
                    it_end = str(it.extra.get("end") or "?")
                    capacity = it.extra.get("capacity")
                    committed = it.extra.get("committed_points")
                    entry = (
                        f"- {it.id} (iteration {number}): "
                        f"{it_start} to {it_end}"
                    )
                    if capacity not in (None, ""):
                        entry += f", capacity {capacity}"
                    if committed not in (None, ""):
                        entry += f", committed {committed}"
                    lines.append(entry)
            lines.append("")

            pi_objs = [
                o for o in objectives if pi.id in _ref_targets(o, "part_of")
            ]
            lines.append("Objectives:")
            if not pi_objs:
                lines.append("- _None yet._")
            else:
                for obj in pi_objs:
                    bv = obj.extra.get("business_value")
                    entry = f"- {obj.id}: {obj.name}"
                    if bv not in (None, ""):
                        entry += f" (bv {bv})"
                    supports = _ref_targets(obj, "supported_by")
                    if supports:
                        entry += f" <- {', '.join(supports)}"
                    lines.append(entry)
            lines.append("")

    # --- Backlog by State ---
    lines.append("## Backlog by State")
    lines.append("")

    work_items = _nodes_of_kind(nodes, "feature") + _nodes_of_kind(nodes, "story")
    if not work_items:
        lines.append("_None yet._")
        lines.append("")
    else:
        by_state: dict[str, list[NodeFile]] = {}
        for item in work_items:
            state = str(item.extra.get("state") or "(no state)")
            by_state.setdefault(state, []).append(item)

        ordered_states = [s for s in _BACKLOG_STATE_ORDER if s in by_state]
        ordered_states += sorted(s for s in by_state if s not in _BACKLOG_STATE_ORDER)

        for state in ordered_states:
            lines.append(f"### {state}")
            for item in sorted(by_state[state], key=lambda n: n.id):
                entry = f"- {item.id}: {item.name}"
                if item.kind == "feature":
                    score = _wsjf_score(item)
                    if score:
                        entry += f" (wsjf {score})"
                else:
                    points = _story_points(item)
                    if points:
                        entry += f" ({points} pts)"
                lines.append(entry)
            lines.append("")

    # --- Traceability ---
    lines.append("## Traceability")
    lines.append("")

    # realizes refs point child -> parent; invert into a children map.
    children: dict[str, list[NodeFile]] = {}
    for node in nodes.values():
        if node.kind not in ("capability", "feature", "story"):
            continue
        for parent_id in _ref_targets(node, "realizes"):
            children.setdefault(parent_id, []).append(node)

    def _render_chain(parent_id: str, depth: int, seen: set[str]) -> None:
        for child in sorted(children.get(parent_id, []), key=lambda n: n.id):
            if child.id in seen:
                continue
            seen.add(child.id)
            lines.append(f"{'  ' * depth}- {child.id}: {child.name}")
            _render_chain(child.id, depth + 1, seen)

    epics = _nodes_of_kind(nodes, "epic")
    if not epics:
        lines.append("_None yet._")
    else:
        for epic in epics:
            lines.append(f"- {epic.id}: {epic.name}")
            _render_chain(epic.id, 1, {epic.id})
        lines.append("")

    lines.append("")
    return "\n".join(lines)
