"""Generate markdown view files from Akemi graph nodes.

Replaces rebuild-views.sh with pure Python.  Produces five view files
in ``.akemi/graph/views/``:

  - ``architecture.md``  -- domains, module dependencies, tech stack
  - ``api-surface.md``   -- API endpoint listing
  - ``test-coverage.md`` -- covered / not-covered map
  - ``dependency-tree.md`` -- module dependency tree with all ref types
  - ``tech-stack.md``    -- technology table
"""

from __future__ import annotations

from pathlib import Path

from .node import NodeFile, read_all_nodes
from .paths import now_iso


def rebuild_views(akemi_dir: str | Path) -> str:
    """Generate all 5 view files in ``.akemi/graph/views/``.

    Returns a summary string.
    """
    akemi_dir = Path(akemi_dir)
    nodes_dir = akemi_dir / "graph" / "nodes"
    views_dir = akemi_dir / "graph" / "views"
    views_dir.mkdir(parents=True, exist_ok=True)

    nodes = read_all_nodes(nodes_dir)
    timestamp = now_iso()

    (views_dir / "architecture.md").write_text(
        _architecture_view(nodes, timestamp), encoding="utf-8"
    )
    (views_dir / "api-surface.md").write_text(
        _api_surface_view(nodes, timestamp), encoding="utf-8"
    )
    (views_dir / "test-coverage.md").write_text(
        _test_coverage_view(nodes, timestamp), encoding="utf-8"
    )
    (views_dir / "dependency-tree.md").write_text(
        _dependency_tree_view(nodes, timestamp), encoding="utf-8"
    )
    (views_dir / "tech-stack.md").write_text(
        _tech_stack_view(nodes, timestamp), encoding="utf-8"
    )

    return f"Views rebuilt at {timestamp}"


# ---------------------------------------------------------------------------
# Internal view builders
# ---------------------------------------------------------------------------


def _nodes_of_kind(nodes: dict[str, NodeFile], kind: str) -> list[NodeFile]:
    """Return nodes of a given kind, sorted by ID for deterministic output."""
    return sorted(
        (n for n in nodes.values() if n.kind == kind),
        key=lambda n: n.id,
    )


def _architecture_view(nodes: dict[str, NodeFile], timestamp: str) -> str:
    """Generate ``architecture.md``.

    Sections:
      - Domains: each domain with its contained modules
      - Module Dependencies: ``mod-a -> mod-b, mod-c``
      - Tech Stack: technology name and version
    """
    lines: list[str] = [
        "# Architecture Overview",
        "",
        f"> Auto-generated by Akemi at {timestamp}. Do not edit manually.",
        "",
    ]

    # --- Domains ---
    lines.append("## Domains")
    lines.append("")

    domains = _nodes_of_kind(nodes, "domain")
    if not domains:
        lines.append("_No domains defined yet._")
    else:
        for dom in domains:
            lines.append(f"### {dom.name} ({dom.id})")
            contains = [r.to for r in dom.refs if r.rel == "contains"]
            for target in contains:
                lines.append(f"- {target}")
            lines.append("")

    # --- Module Dependencies ---
    lines.append("## Module Dependencies")
    lines.append("")

    modules = _nodes_of_kind(nodes, "module")
    if not modules:
        lines.append("_No modules defined yet._")
    else:
        for mod in modules:
            deps = [r.to for r in mod.refs if r.rel == "depends_on"]
            if deps:
                lines.append(f"{mod.id} -> {', '.join(deps)}")
    lines.append("")

    # --- Tech Stack ---
    lines.append("## Tech Stack")
    lines.append("")

    techs = _nodes_of_kind(nodes, "technology")
    if not techs:
        lines.append("_No technologies defined yet._")
    else:
        for tech in techs:
            version = tech.extra.get("version", "")
            if version:
                lines.append(f"- {tech.name} {version}")
            else:
                lines.append(f"- {tech.name}")

    lines.append("")
    return "\n".join(lines)


def _api_surface_view(nodes: dict[str, NodeFile], timestamp: str) -> str:
    """Generate ``api-surface.md``.

    Lists all API nodes with method, path_pattern, and auth fields.
    """
    lines: list[str] = [
        "# API Surface",
        "",
        f"> Auto-generated by Akemi at {timestamp}. Do not edit manually.",
        "",
    ]

    apis = _nodes_of_kind(nodes, "api")
    if not apis:
        lines.append("_No API endpoints defined yet._")
    else:
        for api in apis:
            method = api.extra.get("method", "")
            path_pattern = api.extra.get("path_pattern", "")
            auth = api.extra.get("auth", "")
            lines.append(
                f"- **{method} {path_pattern}** ({api.id}) - auth: {auth}"
            )

    lines.append("")
    return "\n".join(lines)


def _test_coverage_view(nodes: dict[str, NodeFile], timestamp: str) -> str:
    """Generate ``test-coverage.md``.

    Sections:
      - Covered: entities that have test nodes with ``tests`` refs
      - Not Covered: classes/functions without any test coverage
    """
    lines: list[str] = [
        "# Test Coverage Map",
        "",
        f"> Auto-generated by Akemi at {timestamp}. Do not edit manually.",
        "",
    ]

    # Collect all tested entity IDs and the test nodes that cover them.
    test_nodes = _nodes_of_kind(nodes, "test")

    # Map: tested_entity_id -> list of test node IDs that cover it.
    tested_by: dict[str, list[str]] = {}
    for tn in test_nodes:
        for ref in tn.refs:
            if ref.rel == "tests":
                tested_by.setdefault(ref.to, []).append(tn.id)

    # --- Covered ---
    lines.append("## Covered")
    lines.append("")

    if not tested_by:
        lines.append("_No test mappings yet._")
    else:
        for entity_id in sorted(tested_by.keys()):
            for test_id in sorted(tested_by[entity_id]):
                lines.append(f"- {entity_id} <- {test_id}")
    lines.append("")

    # --- Not Covered ---
    lines.append("## Not Covered")
    lines.append("")

    tested_ids = set(tested_by.keys())
    uncovered: list[NodeFile] = []
    for node in sorted(nodes.values(), key=lambda n: n.id):
        if node.kind in ("class", "function") and node.id not in tested_ids:
            uncovered.append(node)

    if not uncovered:
        lines.append("_All entities have test coverage._")
    else:
        for node in uncovered:
            lines.append(f"- {node.id} ({node.name}) - NO TESTS")

    lines.append("")
    return "\n".join(lines)


def _dependency_tree_view(nodes: dict[str, NodeFile], timestamp: str) -> str:
    """Generate ``dependency-tree.md``.

    For each module, lists ALL refs (not just depends_on).
    """
    lines: list[str] = [
        "# Dependency Tree",
        "",
        f"> Auto-generated by Akemi at {timestamp}. Do not edit manually.",
        "",
    ]

    modules = _nodes_of_kind(nodes, "module")
    if not modules:
        lines.append("_No modules defined yet._")
    else:
        for mod in modules:
            lines.append(f"## {mod.name} ({mod.id})")
            if mod.refs:
                for ref in mod.refs:
                    lines.append(f"- --{ref.rel}--> {ref.to}")
            lines.append("")

    lines.append("")
    return "\n".join(lines)


def _tech_stack_view(nodes: dict[str, NodeFile], timestamp: str) -> str:
    """Generate ``tech-stack.md``.

    Renders a markdown table: ``| Technology | Category | Version |``
    """
    lines: list[str] = [
        "# Tech Stack",
        "",
        f"> Auto-generated by Akemi at {timestamp}. Do not edit manually.",
        "",
    ]

    techs = _nodes_of_kind(nodes, "technology")
    if not techs:
        lines.append("_No technologies defined yet._")
    else:
        lines.append("| Technology | Category | Version |")
        lines.append("|-----------|----------|---------|")
        for tech in techs:
            category = tech.extra.get("category", "n/a") or "n/a"
            version = tech.extra.get("version", "n/a") or "n/a"
            lines.append(f"| {tech.name} | {category} | {version} |")

    lines.append("")
    return "\n".join(lines)
